# Interactive documents {#interactive}

- R Markdown leverages Shiny at its core to make this possible. Add runtime: shiny to the document’s YAML header.
- [http://rmarkdown.rstudio.com/authoring_shiny.html](http://rmarkdown.rstudio.com/authoring_shiny.html)
- [http://shiny.rstudio.com/articles/interactive-docs.html](http://shiny.rstudio.com/articles/interactive-docs.html)
- [https://blog.rstudio.org/2014/06/19/interactive-documents-an-incredibly-easy-way-to-use-shiny/](https://blog.rstudio.org/2014/06/19/interactive-documents-an-incredibly-easy-way-to-use-shiny/)
- [http://rmarkdown.rstudio.com/flexdashboard/shiny.html](http://rmarkdown.rstudio.com/flexdashboard/shiny.html)
- As of Spring 17 - Shiny apps can’t currently be embedded into R Notebooks.

## Combining RMarkdown and Shiny

Interactive Documents are an R Markdown file that contains Shiny components and can be an app or used within a report

### Types of Interactive Documents:

- 1. RMD Interactive Document/Report with Shiny components 
- Example: Demo by using File > New > RMarkdown > Shiny > Shiny Document
- 2. HTML presentations with Embed Shiny components
- Example: Demo by using File > New > RMarkdown > Shiny > Shiny Presentation
- *1/2 Note*. It is also possible to embed an entire shiny application within an R Markdown document using the `shinyAppDir` function or `shinyAppFile` or source
- http://rmarkdown.rstudio.com/authoring_embedded_shiny.html
- 3. R Markdown report as Shiny app
- Example [https://jjallaire.shinyapps.io/shiny-ggplot2-brushing/](https://jjallaire.shinyapps.io/shiny-ggplot2-brushing/)

## Include Markdown content in a Shiny app

- It's possible to include files with HTML, text, or Markdown content in a Shiny app.
- [http://shiny.rstudio.com/gallery/including-html-text-and-markdown-files.html](http://shiny.rstudio.com/gallery/including-html-text-and-markdown-files.html)
- The includeMarkdown function requires the markdown package.
- [https://shiny.rstudio.com/reference/shiny/latest/include.html](https://shiny.rstudio.com/reference/shiny/latest/include.html)

## Include Markdown content in a Shiny app - Example

- [https://github.com/abhik1368/openfda-dashboard](https://github.com/abhik1368/openfda-dashboard)
- [https://raw.githubusercontent.com/abhik1368/openfda-dashboard/master/ui.R](https://raw.githubusercontent.com/abhik1368/openfda-dashboard/master/ui.R)
- [https://diabetescheck.shinyapps.io/openfda-dashboard/](https://diabetescheck.shinyapps.io/openfda-dashboard/)